### ISSUE TITLE
Doesnt work on 10.13.6

### ISSUE THREAD

**Issue by ztik** [lanylow/rbxfpsunlocker-osx#4]
Can you guys make it for high sierra 10.13.6 too? Please, thank you have a great day.

**Comment by lanylow** [comment]
What's the problem? Any errors or something?

**Comment by ztik** [comment]
> What's the problem? Any errors or something?

Yes: 

  Referenced from: /Users/nousername/Downloads/./rbxfpsunlocker (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/nousername/Downloads/./rbxfpsunlocker (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by lanylow** [comment]
Can you try compiling the program yourself and see if it works?

**Comment by ztik** [comment]
> Can you try compiling the program yourself and see if it works?

Hey thanks for saying that! I have compiled it and it works on mac 10.13.6 high sierra like a charm, Can i have permission to put the file on my profile for mac high sierra 10.13.6 users?

**Comment by lanylow** [comment]
You can send the file packed in a .zip here and I will add it to the current release.

**Comment by ztik** [comment]
> You can send the file packed in a .zip here and I will add it to the current release.
[rbxfpsunlocker.zip](https://github.com/lanylow/rbxfpsunlocker-osx/files/8008173/rbxfpsunlocker.zip)

**Comment by lanylow** [comment]
Thanks.
